export const pinnedChats = [
  {
    id: 1,
    name: "Advanced Mathematics",
    type: "class",
    avatar: "https://images.unsplash.com/photo-1453728013993-6d66e9c9123a?w=40&h=40&fit=crop",
    lastMessage: "Today's assignment is available in resources",
    timestamp: "2m",
    unreadCount: 5,
    isTyping: false,
    participants: 28,
  },
  {
    id: 2,
    name: "Physics Study Group",
    type: "group",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&crop=face",
    lastMessage: "Can someone explain quantum mechanics?",
    timestamp: "15m",
    unreadCount: 3,
    isTyping: true,
    participants: 12,
  },
];

export const allChats = [
  {
    id: 3,
    name: "Sarah Johnson",
    type: "student",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b9d0481e?w=40&h=40&fit=crop&crop=face",
    lastMessage: "Thank you for the feedback on my assignment!",
    timestamp: "1h",
    unreadCount: 1,
    isTyping: false,
  },
  {
    id: 4,
    name: "Chemistry Lab B",
    type: "class",
    avatar: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=40&h=40&fit=crop",
    lastMessage: "Lab report submissions due tomorrow",
    timestamp: "2h",
    unreadCount: 0,
    isTyping: false,
    participants: 24,
  },
  {
    id: 5,
    name: "Alex Chen",
    type: "student",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&crop=face",
    lastMessage: "Could we schedule office hours this week?",
    timestamp: "3h",
    unreadCount: 0,
    isTyping: false,
  },
  {
    id: 6,
    name: "History Discussion",
    type: "group",
    avatar: "https://images.unsplash.com/photo-1511367461989-f85a21fda167?w=40&h=40&fit=crop",
    lastMessage: "What are your thoughts on the Renaissance period?",
    timestamp: "5h",
    unreadCount: 2,
    isTyping: false,
    participants: 8,
  },
  {
    id: 7,
    name: "Literature Club",
    type: "group",
    avatar: "https://images.unsplash.com/photo-1511367461989-f85a21fda167?w=40&h=40&fit=crop",
    lastMessage: "Has everyone read the assigned chapters?",
    timestamp: "6h",
    unreadCount: 1,
    isTyping: false,
    participants: 10,
  },
  {
    id: 8,
    name: "Art History",
    type: "class",
    avatar: "https://images.unsplash.com/photo-1511367461989-f85a21fda167?w=40&h=40&fit=crop",
    lastMessage: "Don't forget to submit your essays!",
    timestamp: "7h",
    unreadCount: 0,
    isTyping: false,
    participants: 20,
  }
];

export const initialMessages = [
  {
    id: 1,
    sender: "Sarah Johnson",
    senderType: "student",
    timestamp: "10:30 AM",
    content: "Good morning! I have a question about today's assignment.",
    type: "text",
  },
  {
    id: 2,
    sender: "You",
    senderType: "teacher",
    timestamp: "10:32 AM",
    content: "Good morning Sarah! I'd be happy to help. What's your question?",
    type: "text",
  },
  {
    id: 3,
    sender: "Sarah Johnson",
    senderType: "student",
    timestamp: "10:33 AM",
    content: "I'm having trouble with problem #5. Could you explain the approach?",
    type: "text",
  },
  {
    id: 4,
    sender: "You",
    senderType: "teacher",
    timestamp: "10:35 AM",
    content: {
      filename: "math_problem_solution.pdf",
      size: "2.4 MB",
      url: "#",
    },
    type: "file",
  },
  {
    id: 5,
    sender: "You",
    senderType: "teacher",
    timestamp: "10:36 AM",
    content: "I've attached a step-by-step solution. The key is to break it down into smaller parts first.",
    type: "text",
  },
];
